//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ausleihe_Spiel
    {
        public int Ausleihe_Spiel_ID { get; set; }
        public Nullable<int> Ausleihe_ID { get; set; }
        public Nullable<int> Spiel_ID { get; set; }
        public string Name { get; set; }
        public System.DateTime DatumVon { get; set; }
        public System.DateTime DatumBis { get; set; }
        public int AnzVerlaengerungen { get; set; }
    
        public virtual Ausleihe Ausleihe { get; set; }
        public virtual Spiel Spiel { get; set; }
    }
}
