
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Model
{

using System;
    using System.Collections.Generic;
    
public partial class Code
{

    public int Code_ID { get; set; }

    public string Code1 { get; set; }

    public bool Aktiv { get; set; }

    public Nullable<bool> IsCode { get; set; }

    public Nullable<bool> IsMitarbeiter { get; set; }

    public Nullable<bool> IsAdmin { get; set; }

}

}
